<a href="https://colab.research.google.com/github/KyunghoonJeon/TensorflowIntro/blob/main/chap3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow.compat.v1 as tf

tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [ ]:
hello=tf.constant('Hello, TensorFlow!')
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [ ]:
a=tf.constant(10)
b=tf.constant(32)
c=tf.add(a,b)
print(c)

Tensor("Add:0", shape=(), dtype=int32)


In [ ]:
sess=tf.Session()

print(sess.run(hello))
print(sess.run([a,b,c]))

sess.close()

b'Hello, TensorFlow!'
[10, 32, 42]


In [ ]:
# None은 크기가 정해지지 않았음을 의미
X=tf.placeholder(tf.float32, [None, 3])
print(X)

Tensor("Placeholder:0", shape=(?, 3), dtype=float32)


In [ ]:
x_data=[[1,2,3],[4,5,6]]

In [ ]:
W=tf.Variable(tf.random_normal([3,2]))
b=tf.Variable(tf.random_normal([2,1]))

In [ ]:
expr = tf.matmul(X, W) + b

In [ ]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

print("=== x_data ===")
print(x_data)
print("=== W ===")
print(sess.run(W))
print("=== b ===")
print(sess.run(b))
print("=== expr ===")
print(sess.run(expr, feed_dict={X :x_data}))

sess.close()

=== x_data ===
[[1, 2, 3], [4, 5, 6]]
=== W ===
[[-0.51927835 -0.13353474]
 [ 0.5277273   1.013344  ]
 [ 0.43539    -1.4617987 ]]
=== b ===
[[0.10794076]
 [1.3689821 ]]
=== expr ===
[[ 1.950287  -2.3843021]
 [ 4.5428452 -2.869229 ]]


In [ ]:
x_data=[1,2,3]
y_data=[1,2,3]

In [ ]:
W=tf.Variable(tf.random_uniform([1], -1.0,1.0))
b=tf.Variable(tf.random_uniform([1], -1.0,1.0))

In [ ]:
X=tf.placeholder(tf.float32, name="X")
Y=tf.placeholder(tf.float32, name="Y")

In [ ]:
print(X)
print(Y)

Tensor("X:0", dtype=float32)
Tensor("Y:0", dtype=float32)


In [ ]:
hypothesis = W*X+b

In [ ]:
cost=tf.reduce_mean(tf.square(hypothesis - Y))

In [ ]:
optimizer=tf.train.GradientDescentOptimizer(learning_rate=0.1)
train_op=optimizer.minimize(cost)

In [ ]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    for step in range(100):
        _, cost_val = sess.run([train_op, cost], feed_dict={X:x_data,
                                                        Y:y_data})
        print(step, cost_val, sess.run(W), sess.run(b))

    print("X: 5, Y:", sess.run(hypothesis, feed_dict={X:5}))
    print("X: 2.5, Y:", sess.run(hypothesis, feed_dict={X:2.5}))

0 18.754564 [1.2131236] [0.01462507]
1 0.22464938 [1.0083582] [-0.07354937]
2 0.0032765493 [1.029977] [-0.06218279]
3 0.00060404674 [1.0268716] [-0.06173702]
4 0.00054528733 [1.0264863] [-0.06013823]
5 0.00051902723 [1.0258211] [-0.05870509]
6 0.000494369 [1.0252035] [-0.0572925]
7 0.00047088825 [1.0245972] [-0.05591539]
8 0.00044852044 [1.024006] [-0.05457118]
9 0.00042721594 [1.0234288] [-0.05325936]
10 0.00040692044 [1.0228657] [-0.051979]
11 0.00038759026 [1.022316] [-0.05072945]
12 0.00036918055 [1.0217795] [-0.04950995]
13 0.0003516446 [1.021256] [-0.04831977]
14 0.0003349412 [1.020745] [-0.0471582]
15 0.00031903145 [1.0202463] [-0.04602457]
16 0.00030387755 [1.0197595] [-0.04491816]
17 0.0002894432 [1.0192846] [-0.04383834]
18 0.00027569386 [1.018821] [-0.04278452]
19 0.00026259953 [1.0183685] [-0.04175602]
20 0.0002501262 [1.0179269] [-0.04075221]
21 0.00023824426 [1.017496] [-0.03977254]
22 0.00022692647 [1.0170754] [-0.03881643]
23 0.00021614693 [1.016665] [-0.0378833]
24 0.0